CAS/CAS/Models/Education.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CAS.Models
{
    public class Education
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Institute name")]
        [MaxLength(50)]
        public string InstituteName { get; set; }

        [Required]
        [Display(Name = "Degree title")]
        [MaxLength(50)]
        public string DegreeTitle { get; set; }

        [Required]
        [Display(Name = "Degree status")]
        [MaxLength(10)]
        public string DegreeStatus { get; set; }

        [Required]
        [Display(Name = "Subject area")]
        [MaxLength(50)]
        public string SubjectArea { get; set; }

        [Required]
        [Display(Name = "City")]
        [MaxLength(30)]
        public string City { get; set; }

        [Required]
        [MaxLength(30)]
        public string Country { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "From date")]
        public DateTime FromDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "To date")]
        public DateTime ToDate { get; set; }

        [Display(Name = "Grading scale")]
        public double GradingScale { get; set; }

        [Display(Name = "Final GPA")]
        public double FinalGpa { get; set; }

        public string ApplicantId { get; set; }

        public virtual List<Course> Courses { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}

CAS/CAS/Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class EducationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Education/
        public ActionResult Index()
        {
            return View(db.Educations.ToList());
        }


        // GET: /Education/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // GET: /Education/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Education/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,InstituteName,DegreeTitle,DegreeStatus,SubjectArea,City,Country,FromDate,ToDate,GradingScale,FinalGpa")] Education education)
        {
            if (ModelState.IsValid)
            {
                db.Educations.Add(education);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(education);
        }

        // GET: /Education/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // POST: /Education/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,InstituteName,DegreeTitle,DegreeStatus,SubjectArea,City,Country,FromDate,ToDate,GradingScale,FinalGpa")] Education education)
        {
            if (ModelState.IsValid)
            {
                db.Entry(education).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(education);
        }

        // GET: /Education/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // POST: /Education/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Education education = db.Educations.Find(id);
            db.Educations.Remove(education);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Controllers/EmploymentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class EmploymentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Employment/
        public ActionResult Index()
        {
            return View(db.Employments.ToList());
        }

        // GET: /Employment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // GET: /Employment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Employment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,ComnapyName,WebSite,City,Country,FromDate,ToDate,Position,EmployementType,Programming,DataStructur,Networking,DatabaseAdministration,Teaching,Management,Others,OthersPercentage")] Employment employment)
        {
            if (ModelState.IsValid)
            {
                db.Employments.Add(employment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employment);
        }

        // GET: /Employment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // POST: /Employment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,ComnapyName,WebSite,City,Country,FromDate,ToDate,Position,EmployementType,Programming,DataStructur,Networking,DatabaseAdministration,Teaching,Management,Others,OthersPercentage")] Employment employment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employment);
        }

        // GET: /Employment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // POST: /Employment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employment employment = db.Employments.Find(id);
            db.Employments.Remove(employment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Controllers/EnglishProficiencyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class EnglishProficiencyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /EnglishProficiency/
        public ActionResult Index()
        {
            var englishproficiencies = db.EnglishProficiencies.Include(e => e.Applicant).Include(e => e.Gre).Include(e => e.Ielts).Include(e => e.Toefl);
            return View(englishproficiencies.ToList());
        }

        // GET: /EnglishProficiency/Information
        public ActionResult Information()
        {
            if (db.EnglishProficiencies.Find(User.Identity.Name) == null)
                return RedirectToAction("Create");
            return RedirectToAction("Edit");
        }

        // GET: /EnglishProficiency/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnglishProficiency englishproficiency = db.EnglishProficiencies.Find(id);
            if (englishproficiency == null)
            {
                return HttpNotFound();
            }
            return View(englishproficiency);
        }

        // GET: /EnglishProficiency/Create
        public ActionResult Create()
        {
            //ViewBag.Email = new SelectList(db.Applicants, "Email", "LastName");
            return View();
        }

        // POST: /EnglishProficiency/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email,Reading,Writting,Listening,Speaking,Toefl,Gre,Ielts")] EnglishProficiency englishproficiency)
        {
            if (ModelState.IsValid)
            {
                db.EnglishProficiencies.Add(englishproficiency);
                db.SaveChanges();
                return RedirectToAction("Education", "Index");
            }

            return View(englishproficiency);
        }

        // GET: /EnglishProficiency/Edit/5
        public ActionResult Edit()
        {
            EnglishProficiency englishproficiency = db.EnglishProficiencies.Include(e => e.Toefl).Include(e => e.Gre).Include(e => e.Ielts).SingleOrDefault(e => e.Email == User.Identity.Name);
            if (englishproficiency == null)
            {
                return HttpNotFound();
            }
            return View(englishproficiency);
        }

        // POST: /EnglishProficiency/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email,Reading,Writting,Listening,Speaking,Toefl,Gre,Ielts")] EnglishProficiency englishproficiency)
        {
            if (ModelState.IsValid)
            {
                db.Entry(englishproficiency).State = EntityState.Modified;
                db.Entry(englishproficiency.Toefl).State = EntityState.Modified;
                db.Entry(englishproficiency.Gre).State = EntityState.Modified;
                db.Entry(englishproficiency.Ielts).State = EntityState.Modified;
                db.SaveChanges();
                
                ViewBag.Message = "Update Successful.";
            }            
            return View(englishproficiency);
        }

        // GET: /EnglishProficiency/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EnglishProficiency englishproficiency = db.EnglishProficiencies.Find(id);
            if (englishproficiency == null)
            {
                return HttpNotFound();
            }
            return View(englishproficiency);
        }

        // POST: /EnglishProficiency/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            EnglishProficiency englishproficiency = db.EnglishProficiencies.Find(id);
            db.EnglishProficiencies.Remove(englishproficiency);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Views/Education/Delete.cshtml
@model CAS.Models.Education

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Education</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InstituteName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstituteName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DegreeTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DegreeTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradingScale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradingScale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalGpa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalGpa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CAS/CAS/Views/Education/Details.cshtml
@model CAS.Models.Education

@{
    ViewBag.Title = "Educational Information";
}

<h2>Educational Information</h2>

<div>
    <h4>Details</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InstituteName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstituteName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DegreeTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DegreeTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradingScale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradingScale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalGpa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalGpa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CAS/CAS/Views/Education/Index.cshtml
@model IEnumerable<CAS.Models.Education>

@{
    ViewBag.Title = "Educational Information";
}

<h2>Educational Information</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InstituteName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DegreeTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectArea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.GradingScale)
        </th>
        <th>
            GPA
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.InstituteName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DegreeTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectArea)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.GradingScale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinalGpa)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<hr />
<div>
    @Html.ActionLink("« English Proficiency", "Information", "EnglishProficiency", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Employment Information »", "Index", "Employment", null, new { @class = "btn btn-primary btn-large" })
</div>