CAS/CAS/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class ApplicantController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Applicant/
        public ActionResult Index()
        {
            var applicants = db.Applicants.Include(a => a.Application).Include(a => a.EnglishProficiency);
            return View(applicants.ToList());
        }

        // GET: /Applicant/PersonalInformation
        public ActionResult PersonalInformation()
        {
            if (db.Applicants.Find(User.Identity.Name) == null)
                return RedirectToAction("Create");
            return RedirectToAction("Edit");
        }

        // GET: /Applicant/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // GET: /Applicant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Applicant/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email,FirstName,MiddleName,LastName,Gender,MarritalStatus,DateOfBirth,CountryOfCitizen,CountryOfBirth,CurrentCity,VisaStatus,Skype,PhoneHome,PhoneWork,IsAppliedBefore")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                db.Applicants.Add(applicant);
                db.SaveChanges();

                ////Create Application Starting informaiton with status
                //Application application = new Application();
                //application.Email = User.Identity.Name;
                //application.StartDate = DateTime.Now;
                //application.IsSubmitted = false;
                
                //db.Applications.Add(application);
                //db.SaveChanges();

                return RedirectToAction("Information", "EnglishProficiency");
            }

            return View(applicant);
        }

        // GET: /Applicant/Edit
        public ActionResult Edit()
        {
            Applicant applicant = db.Applicants.Find(User.Identity.Name);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // POST: /Applicant/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email,FirstName,MiddleName,LastName,Gender,MarritalStatus,DateOfBirth,CountryOfCitizen,CountryOfBirth,CurrentCity,VisaStatus,Skype,PhoneHome,PhoneWork,IsAppliedBefore")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicant).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Message = "Update Successful.";
            }
            return View(applicant);
        }

        // GET: /Applicant/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        // POST: /Applicant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Applicant applicant = db.Applicants.Find(id);
            db.Applicants.Remove(applicant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Controllers/HomeController.cs
using CAS.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CAS.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            if (db.Applicants.Find(User.Identity.Name) == null)
                ViewBag.IsNew = true;
            else
                ViewBag.IsNew = false;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Compro Application System.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Compro Application System.";

            return View();
        }
    }
}

CAS/CAS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    The aim of this project is to develop an easy and efficient online application system to apply for M.Sc in Computer Science degree
    under the Maharishi University of Management.
</p>

CAS/CAS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Maharishi University of Management<br />
    1000 N 4th St, Fairfield, Iowa-52557<br />
    <abbr title="Phone">P:</abbr>
    641.472.1153
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:mscs_mum@mum.edu">mscs_mum@mum.edu</a><br />
</address>

CAS/CAS/Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p class="lead">Welcome to the applicaiton management system.</p>
    <br /><br />
    @if (ViewBag.IsNew)
    {
        <p>@Html.ActionLink("Start New Application »", "Create", "Applicant", null, new { @class = "btn btn-primary btn-large" })</p>
    }
    else
    {
        <p>@Html.ActionLink("Update Application »", "Edit", "Applicant", null, new { @class = "btn btn-primary btn-large" })</p>
    }
</div>
<br /> <br /> <br /> <br /> <br /> <br /><br /><br /><br />
<!--
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
-->