CAS/CAS/Models/Employment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CAS.Models
{
    public class Employment
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string ComnapyName { get; set; }

        [MaxLength(50)]
        public string WebSite { get; set; }

        [Required]
        [MaxLength(20)]
        public string City { get; set; }

        [Required]
        [MaxLength(2)]
        public string Country { get; set; }

        [Required]
        public DateTime FromDate { get; set; }

        [Required]
        public DateTime ToDate { get; set; }

        [Required]
        [MaxLength(30)]
        public string Position { get; set; }

        [Required]
        [MaxLength(10)]
        public string EmployementType { get; set; }

        [Required]
        public double Programming { get; set; }

        [Required]
        public double DataStructur { get; set; }

        [Required]
        public double Networking { get; set; }

        [Required]
        public double DatabaseAdministration { get; set; }
        
        [Required]
        public double Teaching { get; set; }

        [Required]
        public double Management { get; set; }

        [MaxLength(50)]
        public string Others { get; set; }

        public double OthersPercentage { get; set; }

        public virtual Applicant Applicant { get; set; }
    }
}

CAS/CAS/Controllers/AwardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class AwardsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Awards/
        public ActionResult Index()
        {
            return View(db.AwardsAndHonors.ToList());
        }

        // GET: /Awards/Honours
        public ActionResult Honours()
        {
            if (db.AwardsAndHonors.Find(User.Identity.Name) == null)
                return RedirectToAction("Create");
            return RedirectToAction("Edit");
        }

        // GET: /Awards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AwardsAndHonors awardsandhonors = db.AwardsAndHonors.Find(id);
            if (awardsandhonors == null)
            {
                return HttpNotFound();
            }
            return View(awardsandhonors);
        }

        // GET: /Awards/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Awards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Year,Description")] AwardsAndHonors awardsandhonors)
        {
            if (ModelState.IsValid)
            {
                db.AwardsAndHonors.Add(awardsandhonors);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(awardsandhonors);
        }

        // GET: /Awards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AwardsAndHonors awardsandhonors = db.AwardsAndHonors.Find(id);
            if (awardsandhonors == null)
            {
                return HttpNotFound();
            }
            return View(awardsandhonors);
        }

        // POST: /Awards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Year,Description")] AwardsAndHonors awardsandhonors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(awardsandhonors).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(awardsandhonors);
        }

        // GET: /Awards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AwardsAndHonors awardsandhonors = db.AwardsAndHonors.Find(id);
            if (awardsandhonors == null)
            {
                return HttpNotFound();
            }
            return View(awardsandhonors);
        }

        // POST: /Awards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AwardsAndHonors awardsandhonors = db.AwardsAndHonors.Find(id);
            db.AwardsAndHonors.Remove(awardsandhonors);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class EducationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Education/
        public ActionResult Index()
        {
            return View(db.Educations.ToList());
        }


        // GET: /Education/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // GET: /Education/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Education/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,InstituteName,DegreeTitle,DegreeStatus,SubjectArea,City,Country,FromDate,ToDate,GradingScale,FinalGpa")] Education education)
        {
            if (ModelState.IsValid)
            {
                db.Educations.Add(education);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(education);
        }

        // GET: /Education/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // POST: /Education/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,InstituteName,DegreeTitle,DegreeStatus,SubjectArea,City,Country,FromDate,ToDate,GradingScale,FinalGpa")] Education education)
        {
            if (ModelState.IsValid)
            {
                db.Entry(education).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(education);
        }

        // GET: /Education/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Education education = db.Educations.Find(id);
            if (education == null)
            {
                return HttpNotFound();
            }
            return View(education);
        }

        // POST: /Education/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Education education = db.Educations.Find(id);
            db.Educations.Remove(education);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Controllers/EmploymentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CAS.Models;
using CAS.DAL;

namespace CAS.Controllers
{
    public class EmploymentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Employment/
        public ActionResult Index()
        {
            return View(db.Employments.ToList());
        }

        // GET: /Employment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // GET: /Employment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Employment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,ComnapyName,WebSite,City,Country,FromDate,ToDate,Position,EmployementType,Programming,DataStructur,Networking,DatabaseAdministration,Teaching,Management,Others,OthersPercentage")] Employment employment)
        {
            if (ModelState.IsValid)
            {
                db.Employments.Add(employment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employment);
        }

        // GET: /Employment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // POST: /Employment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,ComnapyName,WebSite,City,Country,FromDate,ToDate,Position,EmployementType,Programming,DataStructur,Networking,DatabaseAdministration,Teaching,Management,Others,OthersPercentage")] Employment employment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employment);
        }

        // GET: /Employment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employment employment = db.Employments.Find(id);
            if (employment == null)
            {
                return HttpNotFound();
            }
            return View(employment);
        }

        // POST: /Employment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employment employment = db.Employments.Find(id);
            db.Employments.Remove(employment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAS/CAS/Views/Employment/Create.cshtml
@model CAS.Models.Employment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employment</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ComnapyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComnapyName)
                @Html.ValidationMessageFor(model => model.ComnapyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebSite, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebSite)
                @Html.ValidationMessageFor(model => model.WebSite)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate)
                @Html.ValidationMessageFor(model => model.FromDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate)
                @Html.ValidationMessageFor(model => model.ToDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position)
                @Html.ValidationMessageFor(model => model.Position)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployementType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployementType)
                @Html.ValidationMessageFor(model => model.EmployementType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Programming, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Programming)
                @Html.ValidationMessageFor(model => model.Programming)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataStructur, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataStructur)
                @Html.ValidationMessageFor(model => model.DataStructur)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Networking, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Networking)
                @Html.ValidationMessageFor(model => model.Networking)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatabaseAdministration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatabaseAdministration)
                @Html.ValidationMessageFor(model => model.DatabaseAdministration)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teaching, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teaching)
                @Html.ValidationMessageFor(model => model.Teaching)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Management, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Management)
                @Html.ValidationMessageFor(model => model.Management)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Others, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Others)
                @Html.ValidationMessageFor(model => model.Others)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OthersPercentage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OthersPercentage)
                @Html.ValidationMessageFor(model => model.OthersPercentage)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />
<div>
    @Html.ActionLink("« Educational Information", "Index", "Education", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Awards and Honors »", "Index", "Awards", null, new { @class = "btn btn-primary btn-large" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CAS/CAS/Views/Employment/Edit.cshtml
@model CAS.Models.Employment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employment</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ComnapyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComnapyName)
                @Html.ValidationMessageFor(model => model.ComnapyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebSite, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebSite)
                @Html.ValidationMessageFor(model => model.WebSite)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate)
                @Html.ValidationMessageFor(model => model.FromDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate)
                @Html.ValidationMessageFor(model => model.ToDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position)
                @Html.ValidationMessageFor(model => model.Position)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployementType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployementType)
                @Html.ValidationMessageFor(model => model.EmployementType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Programming, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Programming)
                @Html.ValidationMessageFor(model => model.Programming)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataStructur, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataStructur)
                @Html.ValidationMessageFor(model => model.DataStructur)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Networking, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Networking)
                @Html.ValidationMessageFor(model => model.Networking)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatabaseAdministration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatabaseAdministration)
                @Html.ValidationMessageFor(model => model.DatabaseAdministration)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teaching, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teaching)
                @Html.ValidationMessageFor(model => model.Teaching)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Management, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Management)
                @Html.ValidationMessageFor(model => model.Management)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Others, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Others)
                @Html.ValidationMessageFor(model => model.Others)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OthersPercentage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OthersPercentage)
                @Html.ValidationMessageFor(model => model.OthersPercentage)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hr />
<div>
    @Html.ActionLink("« Educational Information", "Index", "Education", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Awards and Honors »", "Index", "Awards", null, new { @class = "btn btn-primary btn-large" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CAS/CAS/Views/Employment/Index.cshtml
@model IEnumerable<CAS.Models.Employment>

@{
    ViewBag.Title = "Index";
}

<h2>Employement History</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ComnapyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebSite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployementType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Programming)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataStructur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Networking)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatabaseAdministration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teaching)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Management)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Others)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OthersPercentage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ComnapyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WebSite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployementType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Programming)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataStructur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Networking)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatabaseAdministration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teaching)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Management)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Others)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OthersPercentage)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<hr />
<div>
    @Html.ActionLink("« Educational Information", "Index", "Education", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Awards and Honors »", "Index", "Awards", null, new { @class = "btn btn-primary btn-large" })
</div>